from ngshare_exchange import configureExchange

# reference: https://nbgrader.readthedocs.io/en/latest/configuration/jupyterhub_config.html
from nbgrader.auth import JupyterHubAuthPlugin

c = get_config() # noqa 

# nbgrader lab image related config, note that is static in grader lab images for now (fhswf specfic)
# this needs to be rebound/set/overwritten by the spawner at runtime
# Theese config options tell local nbgrader where the notebook execution environment is (something maybe expect a nbgrader_config.py there?)
c.CourseDirectory.root = '/home/test_course1/CourseDirectory/test_course1'
c.CourseDirectory.course_id = "test_course1"

# course specific location of the exchange service
c.Exchange.root = '//home/test_course1/nbgrader_exchange'

c.Exchange.path_includes_course = True
c.Authenticator.plugin_class = JupyterHubAuthPlugin

c.NbGrader.logfile = '/opt/conda/envs/jhub/share/jupyter/nbgrader.log'

# Course ID to course title mapping (autogenerated, do not modify).
c.NbGrader.course_titles = {}