name: Build and Push Base Images

on:
  push:
    paths:
      - "base-images/**/Dockerfile"
      - "base-images/**/*"
      - ".github/workflows/build_base_images.yaml"
  workflow_dispatch:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      images: ${{ steps.changed_dirs.outputs.dirs }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Get changed directories
        id: changed_dirs
        run: |
          changed_dirs=$(git diff --name-only --diff-filter=d ${{ github.event.before }} ${{ github.sha }} | grep '^base-images/' | awk -F/ '{print $2}' | uniq | sed 's/^/"/;s/$/",/')
          changed_dirs=$(echo $changed_dirs | tr -d '\n')
          echo "dirs=[ $changed_dirs ]" 
          echo "dirs=[$changed_dirs]" >> $GITHUB_OUTPUT

  build-and-push-base-images:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.images != '[]' ||  contains(github.event_name, 'workflow_dispatch') }}
    strategy:
      matrix:
        image: ${{fromJson(needs.detect-changes.outputs.images)}}
    uses: ./.github/workflows/reusable-docker-build-push.yml
    with:
      image: ${{ matrix.image }}
      folder:  base-images/${{ matrix.image }}
      
  pull-to-harbor:
    needs: [build-and-push-base-images, detect-changes]
    if: ${{ needs.detect-changes.outputs.images != '[]'  ||  contains(github.event_name, 'workflow_dispatch') }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ${{fromJson(needs.detect-changes.outputs.images)}}
    steps:
      - name: pull
        run: |
          openssl s_client -showcerts -connect harbor.ki.fh-swf.de:443 < /dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > /usr/local/share/ca-certificates/ca.crt && update-ca-certificates
          docker image pull harbor.ki.fh-swf.de/ghcr.io/fhswf/jupyterhub-k8s/${{ matrix.image }}
      
