name: Docker Image CI

on:
  schedule:
    - cron: '18 15 * * *'
  push:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      jupyterhub: ${{ steps.filter.outputs.jupyterhub }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: develop

    - uses: dorny/paths-filter@v2.11.1
      id: filter
      with:
        base: develop
        filters: |
          jupyterhub:
            - 'images/jupyterhub/**'
            - 'packages/**'
            - '.github/workflows/docker-image-ci-dev.yml'
            - '.github/workflows/reusable-docker-build-push.yml'

  build-and-push-hub:
    needs: changes
    if: ${{ needs.changes.outputs.jupyterhub == 'true' }}
    uses: ./.github/workflows/reusable-docker-build-push.yml
    with:
      image: jupyterhub
      
  dispatch-deploy:
    needs: build-and-push-hub
    name: Dispatch a deployment request
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Dispatch to workflows
        run: |
            echo ${{needs.build-and-push-hub.outputs}}
            curl -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.DISPATCH_TOKEN }}" \
            --request POST \
            --data '{"event_type": "deploy_dev", "client_payload": { "tags": "${{ needs.build-and-push-hub.outputs.tags }}", "labels": "${{ needs.build-and-push-hub.outputs.labels }}", "image": "${{ needs.build-and-push-hub.outputs.image }}" }}' https://api.github.com/repos/fhswf/kicluster-deployments/dispatches
