
name: test

env:
  input: |
    var1=a1
    var2=a2
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get changed directories
        id: changed_dirs
        run: |
          echo "${{fromJson(env.input)}}"
          echo << EOF ${{env.input}} EOF