name: Dispatcher
on:
  workflow_dispatch:
    
jobs:
  dispatch:
    name: Dispatch
    env:
      ENV: dev
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Dispatch to workflows
        run: |
            curl -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.DISPATCH_TOKEN }}" \
            --request POST \
            --data '{"event_type": "some_event", "client_payload": { "foo": "bar" }}' https://api.github.com/repos/fhswf/kicluster-deployments/dispatches
