
name: test

env:
  input: |
    var1=a1
    var2=a2
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test1
        id: test1
        run: |
          image_name=`echo "${{env.input}}" | awk -F'=' '{print $2}' | tr -d '[:blank:]' | tr  -s '\n' '-' | sed 's/-$//' ` 
          echo "imagename=$image_name" >> $GITHUB_OUTPUT

      - name: test2
        id: test2
        run: |
          echo "ghcr.io/fhswf/image-${{ steps.test1.outputs.imagename }}"
