name: get package

on:
  workflow_dispatch:

jobs:
  read:
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /orgs/fhswf/packages?package_type=container&page=1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
